AllCops:
  TargetRubyVersion: 2.7
  NewCops: disable
  SuggestExtensions: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"

# enable it later
Style/Documentation:
  Enabled: false

Style/NumericLiterals:
  Enabled: false
